export interface LibraryExercise {
  name: string;
  muscle: string;
  type: 'Livre' | 'Máquina' | 'Cardio';
}

export const EXERCISE_LIBRARY: LibraryExercise[] = [
  // PEITO (CHEST)
  { name: 'Supino Reto (Barra)', muscle: 'Peito', type: 'Livre' },
  { name: 'Supino Reto (Halteres)', muscle: 'Peito', type: 'Livre' },
  { name: 'Supino Inclinado (Barra)', muscle: 'Peito', type: 'Livre' },
  { name: 'Supino Inclinado (Halteres)', muscle: 'Peito', type: 'Livre' },
  { name: 'Supino Declinado (Barra)', muscle: 'Peito', type: 'Livre' },
  { name: 'Crucifixo Reto (Halteres)', muscle: 'Peito', type: 'Livre' },
  { name: 'Crucifixo Inclinado (Halteres)', muscle: 'Peito', type: 'Livre' },
  { name: 'Crossover (Polia Alta)', muscle: 'Peito', type: 'Máquina' },
  { name: 'Crossover (Polia Baixa)', muscle: 'Peito', type: 'Máquina' },
  { name: 'Peck Deck (Voador)', muscle: 'Peito', type: 'Máquina' },
  { name: 'Supino Máquina Vertical', muscle: 'Peito', type: 'Máquina' },
  { name: 'Flexão de Braços', muscle: 'Peito', type: 'Livre' },
  { name: 'Dips (Paralelas - Foco Peito)', muscle: 'Peito', type: 'Livre' },
  { name: 'Pullover (Halter)', muscle: 'Peito', type: 'Livre' },
  { name: 'Press Machine Inclinado', muscle: 'Peito', type: 'Máquina' },
  { name: 'Supino Máquina Articulado', muscle: 'Peito', type: 'Máquina' },
  { name: 'Crucifixo Máquina (Fly)', muscle: 'Peito', type: 'Máquina' },
  { name: 'Press Machine Declinado', muscle: 'Peito', type: 'Máquina' },
  { name: 'Flexão com Peso (Anilha)', muscle: 'Peito', type: 'Livre' },
  { name: 'Flexão Diamante', muscle: 'Peito', type: 'Livre' },
  { name: 'Squeeze Press (Halteres)', muscle: 'Peito', type: 'Livre' },
  { name: 'Crucifixo no Banco Declinado', muscle: 'Peito', type: 'Livre' },
  { name: 'Fly na Polia Média', muscle: 'Peito', type: 'Máquina' },
  { name: 'Flexão de Braços (Pegada Larga)', muscle: 'Peito', type: 'Livre' },
  { name: 'Supino na Smith Machine', muscle: 'Peito', type: 'Máquina' },
  { name: 'Flexão Inclinada', muscle: 'Peito', type: 'Livre' },
  { name: 'Flexão Declinada', muscle: 'Peito', type: 'Livre' },
  { name: 'Flexão de Braços (Joelhos no chão)', muscle: 'Peito', type: 'Livre' },
  { name: 'Supino com Pegada Fechada', muscle: 'Peito', type: 'Livre' },
  { name: 'Supino Unilateral con Halter', muscle: 'Peito', type: 'Livre' },

  // COSTAS (BACK)
  { name: 'Levantamento Terra', muscle: 'Costas', type: 'Livre' },
  { name: 'Barra Fixa (Pronada)', muscle: 'Costas', type: 'Livre' },
  { name: 'Barra Fixa (Supinada)', muscle: 'Costas', type: 'Livre' },
  { name: 'Puxada Aberta (Pulldown)', muscle: 'Costas', type: 'Máquina' },
  { name: 'Puxada Triângulo', muscle: 'Costas', type: 'Máquina' },
  { name: 'Remada Curvada (Barra)', muscle: 'Costas', type: 'Livre' },
  { name: 'Remada Unilateral (Serrote)', muscle: 'Costas', type: 'Livre' },
  { name: 'Remada Cavalinho', muscle: 'Costas', type: 'Máquina' },
  { name: 'Remada Baixa (Triângulo)', muscle: 'Costas', type: 'Máquina' },
  { name: 'Remada Máquina Unilateral', muscle: 'Costas', type: 'Máquina' },
  { name: 'Puxada Braços Estendidos (Pullover)', muscle: 'Costas', type: 'Máquina' },
  { name: 'Face Pull', muscle: 'Costas', type: 'Máquina' },
  { name: 'Hiperextensão Lombar', muscle: 'Costas', type: 'Livre' },
  { name: 'Puxada Romana', muscle: 'Costas', type: 'Máquina' },
  { name: 'Remada Smith', muscle: 'Costas', type: 'Máquina' },
  { name: 'Pulldown com Corda', muscle: 'Costas', type: 'Máquina' },
  { name: 'Remada no Banco Inclinado', muscle: 'Costas', type: 'Livre' },
  { name: 'Puxada Unilateral na Polia', muscle: 'Costas', type: 'Máquina' },
  { name: 'Crucifixo Inverso na Polia', muscle: 'Costas', type: 'Máquina' },
  { name: 'Muscle Up', muscle: 'Costas', type: 'Livre' },
  { name: 'Front Lever (Progressão)', muscle: 'Costas', type: 'Livre' },
  { name: 'Superman (Lombar)', muscle: 'Costas', type: 'Livre' },
  { name: 'Remada Yates', muscle: 'Costas', type: 'Livre' },
  { name: 'T-Bar Row (Remada T)', muscle: 'Costas', type: 'Máquina' },
  { name: 'Remada com Elástico', muscle: 'Costas', type: 'Livre' },
  { name: 'Puxada Horizontal (TRX)', muscle: 'Costas', type: 'Livre' },
  { name: 'Puxada com Pegada Supinada', muscle: 'Costas', type: 'Máquina' },

  // OMBROS (SHOULDERS)
  { name: 'Desenvolvimento Militar (Barra)', muscle: 'Ombros', type: 'Livre' },
  { name: 'Desenvolvimento Halteres', muscle: 'Ombros', type: 'Livre' },
  { name: 'Desenvolvimento Arnold', muscle: 'Ombros', type: 'Livre' },
  { name: 'Elevação Lateral (Halteres)', muscle: 'Ombros', type: 'Livre' },
  { name: 'Elevação Lateral (Polia)', muscle: 'Ombros', type: 'Máquina' },
  { name: 'Elevação Frontal (Barra)', muscle: 'Ombros', type: 'Livre' },
  { name: 'Elevação Frontal (Halteres)', muscle: 'Ombros', type: 'Livre' },
  { name: 'Crucifixo Inverso (Halteres)', muscle: 'Ombros', type: 'Livre' },
  { name: 'Crucifixo Inverso (Peck Deck)', muscle: 'Ombros', type: 'Máquina' },
  { name: 'Desenvolvimento Máquina', muscle: 'Ombros', type: 'Máquina' },
  { name: 'Elevação Lateral Inclinada', muscle: 'Ombros', type: 'Livre' },
  { name: 'Remada Alta na Polia', muscle: 'Ombros', type: 'Máquina' },
  { name: 'Crucifixo Inverso no Banco', muscle: 'Ombros', type: 'Livre' },
  { name: 'Face Pull com Corda', muscle: 'Ombros', type: 'Máquina' },
  { name: 'Clean and Press', muscle: 'Ombros', type: 'Livre' },
  { name: 'Handstand Pushup', muscle: 'Ombros', type: 'Livre' },
  { name: 'Elevação Lateral no Banco 45°', muscle: 'Ombros', type: 'Livre' },
  { name: 'Desenvolvimento Unilateral', muscle: 'Ombros', type: 'Livre' },
  { name: 'Elevação Frontal com Anilha', muscle: 'Ombros', type: 'Livre' },

  // TRAPÉZIO (TRAPS)
  { name: 'Encolhimento (Halteres)', muscle: 'Trapézio', type: 'Livre' },
  { name: 'Encolhimento (Barra)', muscle: 'Trapézio', type: 'Livre' },
  { name: 'Encolhimento no Smith', muscle: 'Trapézio', type: 'Máquina' },
  { name: 'Encolhimento por Trás (Barra)', muscle: 'Trapézio', type: 'Livre' },
  { name: 'Remada Alta Aberta', muscle: 'Trapézio', type: 'Livre' },
  { name: 'Encolhimento com Anilhas', muscle: 'Trapézio', type: 'Livre' },

  // BÍCEPS (BICEPS)
  { name: 'Rosca Direta (Barra W)', muscle: 'Bíceps', type: 'Livre' },
  { name: 'Rosca Direta (Barra Reta)', muscle: 'Bíceps', type: 'Livre' },
  { name: 'Rosca Alternada (Halteres)', muscle: 'Bíceps', type: 'Livre' },
  { name: 'Rosca Martelo (Halteres)', muscle: 'Bíceps', type: 'Livre' },
  { name: 'Rosca Concentrada', muscle: 'Bíceps', type: 'Livre' },
  { name: 'Rosca Scott (Barra ou Máquina)', muscle: 'Bíceps', type: 'Máquina' },
  { name: 'Rosca na Polia Baixa', muscle: 'Bíceps', type: 'Máquina' },
  { name: 'Rosca 21', muscle: 'Bíceps', type: 'Livre' },
  { name: 'Rosca Aranha (Spider Curl)', muscle: 'Bíceps', type: 'Livre' },
  { name: 'Rosca Zottman', muscle: 'Bíceps', type: 'Livre' },
  { name: 'Rosca no Cabo com Corda', muscle: 'Bíceps', type: 'Máquina' },
  { name: 'Rosca Direta no Banco 45', muscle: 'Bíceps', type: 'Livre' },
  { name: 'Rosca Concentrada no Cabo', muscle: 'Bíceps', type: 'Máquina' },
  { name: 'Rosca 21 (Cabo)', muscle: 'Bíceps', type: 'Máquina' },

  // TRÍCEPS (TRICEPS)
  { name: 'Tríceps Pulley (Corda)', muscle: 'Tríceps', type: 'Máquina' },
  { name: 'Tríceps Pulley (Barra V)', muscle: 'Tríceps', type: 'Máquina' },
  { name: 'Tríceps Testa (Barra W)', muscle: 'Tríceps', type: 'Livre' },
  { name: 'Tríceps Coice (Halter ou Polia)', muscle: 'Tríceps', type: 'Livre' },
  { name: 'Tríceps Francês (Halter)', muscle: 'Tríceps', type: 'Livre' },
  { name: 'Mergulho no Banco (Dips)', muscle: 'Tríceps', type: 'Livre' },
  { name: 'Extensão de Tríceps (Máquina)', muscle: 'Tríceps', type: 'Máquina' },
  { name: 'Tríceps Coice na Polia', muscle: 'Tríceps', type: 'Máquina' },
  { name: 'Tríceps Banco (Dips)', muscle: 'Tríceps', type: 'Livre' },
  { name: 'Tríceps Unilateral (Polia)', muscle: 'Tríceps', type: 'Máquina' },
  { name: 'Tríceps Pulley Inverso', muscle: 'Tríceps', type: 'Máquina' },
  { name: 'Tríceps Testa com Halteres', muscle: 'Tríceps', type: 'Livre' },
  { name: 'Tríceps Corda Unilateral', muscle: 'Tríceps', type: 'Máquina' },

  // ANTEBRAÇO (FOREARMS)
  { name: 'Rosca Inversa (Barra)', muscle: 'Antebraço', type: 'Livre' },
  { name: 'Rosca Inversa (Polia)', muscle: 'Antebraço', type: 'Máquina' },
  { name: 'Rosca Pajé (Wrist Roller)', muscle: 'Antebraço', type: 'Livre' },
  { name: 'Flexão de Punho (Barra)', muscle: 'Antebraço', type: 'Livre' },
  { name: 'Extensão de Punho (Barra)', muscle: 'Antebraço', type: 'Livre' },
  { name: 'Rosca Martelo Inversa', muscle: 'Antebraço', type: 'Livre' },
  { name: 'Segurar Anilhas (Pinch Grip)', muscle: 'Antebraço', type: 'Livre' },
  { name: 'Flexão de Punho Suportada', muscle: 'Antebraço', type: 'Livre' },

  // QUADRÍCEPS (QUADS)
  { name: 'Agachamento Livre (Barra)', muscle: 'Quadríceps', type: 'Livre' },
  { name: 'Leg Press 45°', muscle: 'Quadríceps', type: 'Máquina' },
  { name: 'Leg Press Horizontal', muscle: 'Quadríceps', type: 'Máquina' },
  { name: 'Cadeira Extensora', muscle: 'Quadríceps', type: 'Máquina' },
  { name: 'Hack Squat', muscle: 'Quadríceps', type: 'Máquina' },
  { name: 'Afundo (Halteres)', muscle: 'Quadríceps', type: 'Livre' },
  { name: 'Avanço (Passada)', muscle: 'Quadríceps', type: 'Livre' },
  { name: 'Agachamento Sumô', muscle: 'Quadríceps', type: 'Livre' },
  { name: 'Agachamento Búlgaro', muscle: 'Quadríceps', type: 'Livre' },
  { name: 'Goblet Squat (Halter)', muscle: 'Quadríceps', type: 'Livre' },
  { name: 'Agachamento Frontal', muscle: 'Quadríceps', type: 'Livre' },
  { name: 'Agachamento Smith', muscle: 'Quadríceps', type: 'Máquina' },
  { name: 'Afundo no Smith', muscle: 'Quadríceps', type: 'Máquina' },
  { name: 'Sissy Squat', muscle: 'Quadríceps', type: 'Livre' },
  { name: 'Agachamento Isométrico (Parede)', muscle: 'Quadríceps', type: 'Livre' },
  { name: 'Cadeira Extensora (Unilateral)', muscle: 'Quadríceps', type: 'Máquina' },
  { name: 'Agachamento com Peso do Corpo', muscle: 'Quadríceps', type: 'Livre' },
  { name: 'Pistol Squat', muscle: 'Quadríceps', type: 'Livre' },
  { name: 'Agachamento Zercher', muscle: 'Quadríceps', type: 'Livre' },

  // POSTERIORES (HAMSTRINGS)
  { name: 'Mesa Flexora', muscle: 'Posteriores', type: 'Máquina' },
  { name: 'Cadeira Flexora', muscle: 'Posteriores', type: 'Máquina' },
  { name: 'Stiff (Barra ou Halter)', muscle: 'Posteriores', type: 'Livre' },
  { name: 'Mesa Flexora (Unilateral)', muscle: 'Posteriores', type: 'Máquina' },
  { name: 'Bom Dia (Good Morning)', muscle: 'Posteriores', type: 'Livre' },

  // GLÚTEOS (GLUTES)
  { name: 'Elevação de Pélvis (Hip Thrust)', muscle: 'Glúteos', type: 'Livre' },
  { name: 'Glúteo na Polia (Cice)', muscle: 'Glúteos', type: 'Máquina' },
  { name: 'Abdução de Quadril (Polia)', muscle: 'Glúteos', type: 'Máquina' },
  { name: 'Elevação Pélvica na Máquina', muscle: 'Glúteos', type: 'Máquina' },
  { name: 'Frog Pump', muscle: 'Glúteos', type: 'Livre' },
  { name: 'Extensão de Quadril 45°', muscle: 'Glúteos', type: 'Livre' },
  { name: 'Cadeira Abdutora', muscle: 'Glúteos', type: 'Máquina' },
  { name: 'Glúteo Quatro Apoios', muscle: 'Glúteos', type: 'Livre' },

  // PANTURRILHAS (CALVES)
  { name: 'Panturrilha em Pé (Máquina)', muscle: 'Panturrilhas', type: 'Máquina' },
  { name: 'Panturrilha Sentado (Sóleio)', muscle: 'Panturrilhas', type: 'Máquina' },
  { name: 'Panturrilha no Leg Press', muscle: 'Panturrilhas', type: 'Máquina' },
  { name: 'Panturrilha Unilateral', muscle: 'Panturrilhas', type: 'Livre' },
  { name: 'Panturrilha no Smith (Sentado)', muscle: 'Panturrilhas', type: 'Máquina' },

  // ABDÔMEN (CORE)
  { name: 'Abdominal Supra (Solo)', muscle: 'Abdômen', type: 'Livre' },
  { name: 'Abdominal infra (Elevação Pernas)', muscle: 'Abdômen', type: 'Livre' },
  { name: 'Plancha Abdominal', muscle: 'Abdômen', type: 'Livre' },
  { name: 'Abdominal Bicicleta', muscle: 'Abdômen', type: 'Livre' },
  { name: 'Abdominal Roda (Wheel)', muscle: 'Abdômen', type: 'Livre' },
  { name: 'Abdominal Máquina', muscle: 'Abdômen', type: 'Máquina' },
  { name: 'Prancha Lateral', muscle: 'Abdômen', type: 'Livre' },
  { name: 'Russian Twist (Giro Russo)', muscle: 'Abdômen', type: 'Livre' },
  { name: 'Mountain Climbers', muscle: 'Abdômen', type: 'Livre' },
  { name: 'Abdominal na Polia (Reza)', muscle: 'Abdômen', type: 'Máquina' },
  { name: 'Abdominal Oblíquo (Polia)', muscle: 'Abdômen', type: 'Máquina' },
  { name: 'Elevação de Pernas Pendurado', muscle: 'Abdômen', type: 'Livre' },
  { name: 'Prancha Dinâmica', muscle: 'Abdômen', type: 'Livre' },
  { name: 'Woodchopper (Lenhador)', muscle: 'Abdômen', type: 'Máquina' },
  { name: 'Abdominal Infra no Banco', muscle: 'Abdômen', type: 'Livre' },
  { name: 'Dead Bug (Core)', muscle: 'Abdômen', type: 'Livre' },
  { name: 'Bird Dog (Core)', muscle: 'Abdômen', type: 'Livre' },
  { name: 'L-Sit', muscle: 'Abdômen', type: 'Livre' },
  { name: 'Dragon Flag', muscle: 'Abdômen', type: 'Livre' },

  // CARDIO
  { name: 'Esteira (Caminhada/Corrida)', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Bicicleta Ergométrica', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Elíptico (Transport)', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Escada Rolante (Stairmaster)', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Remo Seco (Rowing)', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Pular Corda', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Natação', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Burpees', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Polichinelos', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Sprint HIIT', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Air Bike (Assault Bike)', muscle: 'Cardio', type: 'Cardio' },
  { name: 'SkiErg', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Boxe (Saco de Pancada)', muscle: 'Cardio', type: 'Cardio' },
  { name: 'Battle Ropes', muscle: 'Cardio', type: 'Cardio' },

  // MOBILIDADE / ALONGAMENTO
  { name: 'Alongamento de Peitorais', muscle: 'Mobilidade', type: 'Livre' },
  { name: 'Mobilidade de Quadril (90/90)', muscle: 'Mobilidade', type: 'Livre' },
  { name: 'Cobra Stretch (Lombar)', muscle: 'Mobilidade', type: 'Livre' },
  { name: 'Cat-Cow (Coluna)', muscle: 'Mobilidade', type: 'Livre' },
  { name: 'Child Posture (Criança)', muscle: 'Mobilidade', type: 'Livre' },
  { name: 'Alongamento de Isquiotibiais', muscle: 'Mobilidade', type: 'Livre' },

  // FUNCIONAL / OUTROS
  { name: 'Kettlebell Swing', muscle: 'Funcional', type: 'Livre' },
  { name: 'Farmer Walk', muscle: 'Funcional', type: 'Livre' },
  { name: 'Wall Ball', muscle: 'Funcional', type: 'Livre' },
  { name: 'Box Jump (Salto na Caixa)', muscle: 'Funcional', type: 'Livre' }
];
